IF COL_LENGTH('dbo.USERS', 'EMAIL') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD EMAIL NVARCHAR(255) NULL;
END
GO

-- Normalize existing rows before applying constraints.
UPDATE dbo.USERS
SET EMAIL = LOWER(LTRIM(RTRIM(EMAIL)))
WHERE EMAIL IS NOT NULL;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_USERS_EMAIL'
    AND object_id = OBJECT_ID('dbo.USERS')
)
BEGIN
  CREATE UNIQUE INDEX UX_USERS_EMAIL
  ON dbo.USERS (EMAIL)
  WHERE EMAIL IS NOT NULL;
END
GO
