USE GAMERSHUB_USER;
GO

IF COL_LENGTH('dbo.USER_PROFILE', 'DATE_OF_BIRTH') IS NULL
BEGIN
  ALTER TABLE dbo.USER_PROFILE
  ADD DATE_OF_BIRTH DATE NULL;
END
GO

DECLARE @sql NVARCHAR(MAX) = N'';

SELECT @sql +=
  N'ALTER TABLE dbo.USER_PROFILE ALTER COLUMN ' + QUOTENAME(COLUMN_NAME) + N' ' +
  DATA_TYPE +
  CASE
    WHEN DATA_TYPE IN ('varchar','nvarchar','char','nchar')
      THEN N'(' + CASE WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN N'MAX' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS NVARCHAR(10)) END + N')'
    WHEN DATA_TYPE IN ('decimal','numeric')
      THEN N'(' + CAST(NUMERIC_PRECISION AS NVARCHAR(10)) + N',' + CAST(NUMERIC_SCALE AS NVARCHAR(10)) + N')'
    ELSE N''
  END +
  N' NULL;' + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'USER_PROFILE'
  AND COLUMN_NAME IN (
    'STUDENT_ID',
    'FIRST_NAME',
    'LAST_NAME',
    'PHONE_NUMBER',
    'SCHOOL',
    'PRIMARY_GAME'
  );

IF (@sql <> N'')
BEGIN
  EXEC sp_executesql @sql;
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_USER_PROFILE_USERID'
    AND object_id = OBJECT_ID('dbo.USER_PROFILE')
)
BEGIN
  CREATE UNIQUE INDEX UX_USER_PROFILE_USERID
  ON dbo.USER_PROFILE (USERID);
END
GO

INSERT INTO GAMERSHUB_USER.dbo.USER_PROFILE (
  USERID,
  STUDENT_ID,
  IN_GAME_NAME,
  EMAIL
)
SELECT
  authUsers.USERID,
  CONCAT('TEMP-', authUsers.USERID),
  authUsers.USERNAME,
  authUsers.EMAIL
FROM GAMERSHUB_AUTH.dbo.USERS AS authUsers
WHERE NOT EXISTS (
  SELECT 1
  FROM GAMERSHUB_USER.dbo.USER_PROFILE AS profiles
  WHERE profiles.USERID = authUsers.USERID
);
GO
