/*
  Run these statements when you're ready to support richer player feed metadata
  and real livestream playback details in GAMERSHUB_FEED.

  This script is idempotent and only adds missing columns.
*/

USE GAMERSHUB_FEED;
GO

IF COL_LENGTH('dbo.POST', 'CREATED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.POST
  ADD CREATED_AT DATETIME2 NOT NULL
    CONSTRAINT DF_POST_CREATED_AT DEFAULT SYSDATETIME();
END;
GO

IF COL_LENGTH('dbo.COMMENT', 'CREATED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.COMMENT
  ADD CREATED_AT DATETIME2 NOT NULL
    CONSTRAINT DF_COMMENT_CREATED_AT DEFAULT SYSDATETIME();
END;
GO

IF COL_LENGTH('dbo.STREAM', 'PLAYBACK_URL') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD PLAYBACK_URL NVARCHAR(1000) NULL;
END;
GO

IF COL_LENGTH('dbo.STREAM', 'THUMBNAIL_URL') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD THUMBNAIL_URL NVARCHAR(1000) NULL;
END;
GO

IF COL_LENGTH('dbo.STREAM', 'GAME_NAME') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD GAME_NAME NVARCHAR(100) NULL;
END;
GO

IF COL_LENGTH('dbo.STREAM', 'STREAM_DESCRIPTION') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD STREAM_DESCRIPTION NVARCHAR(MAX) NULL;
END;
GO

IF COL_LENGTH('dbo.STREAM', 'STARTED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD STARTED_AT DATETIME2 NULL;
END;
GO

IF COL_LENGTH('dbo.STREAM', 'ENDED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD ENDED_AT DATETIME2 NULL;
END;
GO
