/*
  Run this when you're ready to persist notifications in SQL Server instead of
  browser localStorage.

  We keep notifications in GAMERSHUB_FEED because they are player activity
  records alongside posts, streams, and stream gifts.
*/

USE GAMERSHUB_FEED;
GO

IF OBJECT_ID('dbo.NOTIFICATION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.NOTIFICATION (
    NOTIFICATION_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    NOTIFICATION_TYPE NVARCHAR(50) NOT NULL,
    TITLE NVARCHAR(150) NOT NULL,
    BODY NVARCHAR(500) NULL,
    LINK_URL NVARCHAR(1000) NULL,
    IS_READ BIT NOT NULL
      CONSTRAINT DF_NOTIFICATION_IS_READ DEFAULT 0,
    CREATED_AT DATETIME2 NOT NULL
      CONSTRAINT DF_NOTIFICATION_CREATED_AT DEFAULT SYSDATETIME(),
    READ_AT DATETIME2 NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_NOTIFICATION_USER_CREATED_AT'
    AND object_id = OBJECT_ID('dbo.NOTIFICATION')
)
BEGIN
  CREATE INDEX IX_NOTIFICATION_USER_CREATED_AT
  ON dbo.NOTIFICATION (USER_ID, CREATED_AT DESC);
END;
GO
