/*
  Run this script in SSMS to create the reaction-service database and tables
  required for post reactions and post comments.
*/

IF DB_ID('GAMERSHUB_REACTION') IS NULL
BEGIN
  CREATE DATABASE GAMERSHUB_REACTION;
END;
GO

USE GAMERSHUB_REACTION;
GO

IF OBJECT_ID('dbo.POST_REACTION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.POST_REACTION (
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    REACTION_TYPE NVARCHAR(20) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL
      CONSTRAINT DF_POST_REACTION_CREATED_AT DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2 NOT NULL
      CONSTRAINT DF_POST_REACTION_UPDATED_AT DEFAULT SYSDATETIME(),
    CONSTRAINT PK_POST_REACTION PRIMARY KEY (POST_ID, USER_ID),
    CONSTRAINT CK_POST_REACTION_TYPE CHECK (REACTION_TYPE IN ('like', 'love', 'wow'))
  );
END;
GO

IF OBJECT_ID('dbo.POST_COMMENT', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.POST_COMMENT (
    COMMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    MESSAGE NVARCHAR(MAX) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL
      CONSTRAINT DF_POST_COMMENT_CREATED_AT DEFAULT SYSDATETIME()
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_POST_REACTION_POST_ID'
    AND object_id = OBJECT_ID('dbo.POST_REACTION')
)
BEGIN
  CREATE INDEX IX_POST_REACTION_POST_ID
  ON dbo.POST_REACTION (POST_ID, REACTION_TYPE);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_POST_COMMENT_POST_ID_CREATED_AT'
    AND object_id = OBJECT_ID('dbo.POST_COMMENT')
)
BEGIN
  CREATE INDEX IX_POST_COMMENT_POST_ID_CREATED_AT
  ON dbo.POST_COMMENT (POST_ID, CREATED_AT);
END;
GO
