/*
  Run this in SSMS to align the POST table with the player feed behavior.

  Text-only posts and media-only posts should both be allowed, so CONTENT,
  MEDIA_URL, and MEDIA_TYPE must all be nullable.
*/

USE GAMERSHUB_FEED;
GO

IF EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'POST'
    AND COLUMN_NAME = 'CONTENT'
    AND IS_NULLABLE = 'NO'
)
BEGIN
  ALTER TABLE dbo.POST
  ALTER COLUMN CONTENT NVARCHAR(MAX) NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'POST'
    AND COLUMN_NAME = 'MEDIA_URL'
    AND IS_NULLABLE = 'NO'
)
BEGIN
  ALTER TABLE dbo.POST
  ALTER COLUMN MEDIA_URL NVARCHAR(500) NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME = 'POST'
    AND COLUMN_NAME = 'MEDIA_TYPE'
    AND IS_NULLABLE = 'NO'
)
BEGIN
  ALTER TABLE dbo.POST
  ALTER COLUMN MEDIA_TYPE NVARCHAR(50) NULL;
END;
GO
