USE GAMERSHUB_AUTH;
GO

IF COL_LENGTH('dbo.USERS', 'CREATED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD CREATED_AT DATETIME2 NULL;
END
GO

UPDATE dbo.USERS
SET CREATED_AT = COALESCE(CREATED_AT, SYSDATETIME())
WHERE CREATED_AT IS NULL;
GO

IF COL_LENGTH('dbo.USERS', 'MFA_ENROLLED') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD MFA_ENROLLED BIT NOT NULL CONSTRAINT DF_USERS_MFA_ENROLLED DEFAULT(0);
END
GO

IF COL_LENGTH('dbo.USERS', 'IS_ACTIVE') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD IS_ACTIVE BIT NOT NULL CONSTRAINT DF_USERS_IS_ACTIVE DEFAULT(1);
END
GO

IF COL_LENGTH('dbo.USERS', 'AUTH_PROVIDER') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD AUTH_PROVIDER NVARCHAR(30) NOT NULL CONSTRAINT DF_USERS_AUTH_PROVIDER DEFAULT('local');
END
GO

IF COL_LENGTH('dbo.USERS', 'GOOGLE_SUB') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD GOOGLE_SUB NVARCHAR(255) NULL;
END
GO

IF COL_LENGTH('dbo.USERS', 'AVATAR_URL') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD AVATAR_URL NVARCHAR(1000) NULL;
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_USERS_GOOGLE_SUB'
    AND object_id = OBJECT_ID('dbo.USERS')
)
BEGIN
  CREATE UNIQUE INDEX UX_USERS_GOOGLE_SUB
  ON dbo.USERS (GOOGLE_SUB)
  WHERE GOOGLE_SUB IS NOT NULL;
END
GO

IF OBJECT_ID('dbo.AUTH_SESSION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.AUTH_SESSION (
    SESSION_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    TOKEN_HASH NVARCHAR(128) NOT NULL,
    EXPIRES_AT DATETIME2 NOT NULL,
    CREATED_AT DATETIME2 NOT NULL CONSTRAINT DF_AUTH_SESSION_CREATED_AT DEFAULT(SYSDATETIME()),
    LAST_SEEN_AT DATETIME2 NOT NULL CONSTRAINT DF_AUTH_SESSION_LAST_SEEN_AT DEFAULT(SYSDATETIME()),
    REVOKED_AT DATETIME2 NULL
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_AUTH_SESSION_TOKEN_HASH'
    AND object_id = OBJECT_ID('dbo.AUTH_SESSION')
)
BEGIN
  CREATE UNIQUE INDEX UX_AUTH_SESSION_TOKEN_HASH
  ON dbo.AUTH_SESSION (TOKEN_HASH);
END
GO

IF OBJECT_ID('dbo.AUDIT_LOG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.AUDIT_LOG (
    AUDIT_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACTOR_USER_ID INT NULL,
    ACTOR_ROLE NVARCHAR(50) NULL,
    ACTION_TYPE NVARCHAR(100) NOT NULL,
    ENTITY_TYPE NVARCHAR(100) NOT NULL,
    ENTITY_ID NVARCHAR(100) NULL,
    DETAILS_JSON NVARCHAR(MAX) NULL,
    CREATED_AT DATETIME2 NOT NULL CONSTRAINT DF_AUDIT_LOG_CREATED_AT DEFAULT(SYSDATETIME())
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_AUDIT_LOG_CREATED_AT'
    AND object_id = OBJECT_ID('dbo.AUDIT_LOG')
)
BEGIN
  CREATE INDEX IX_AUDIT_LOG_CREATED_AT
  ON dbo.AUDIT_LOG (CREATED_AT DESC);
END
GO

USE GAMERSHUB_USER;
GO

IF COL_LENGTH('dbo.USER_PROFILE', 'COURSE_YEAR') IS NULL
BEGIN
  ALTER TABLE dbo.USER_PROFILE
  ADD COURSE_YEAR NVARCHAR(100) NULL;
END
GO

USE GAMERSHUB_FEED;
GO

IF COL_LENGTH('dbo.STREAM', 'IS_VISIBLE') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD IS_VISIBLE BIT NOT NULL CONSTRAINT DF_STREAM_IS_VISIBLE DEFAULT(1);
END
GO

IF COL_LENGTH('dbo.STREAM', 'MODERATED_AT') IS NULL
BEGIN
  ALTER TABLE dbo.STREAM
  ADD MODERATED_AT DATETIME2 NULL;
END
GO
