USE GAMERSHUB_AUTH;
GO

IF COL_LENGTH('dbo.USERS', 'MICROSOFT_SUB') IS NULL
BEGIN
  ALTER TABLE dbo.USERS
  ADD MICROSOFT_SUB NVARCHAR(255) NULL;
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_USERS_MICROSOFT_SUB'
    AND object_id = OBJECT_ID('dbo.USERS')
)
BEGIN
  CREATE UNIQUE INDEX UX_USERS_MICROSOFT_SUB
  ON dbo.USERS (MICROSOFT_SUB)
  WHERE MICROSOFT_SUB IS NOT NULL;
END
GO
