-- Run against GAMERSHUB_FEED database
USE GAMERSHUB_FEED;
GO

-- Add soft tournament reference to STREAM table
ALTER TABLE dbo.STREAM
ADD TOURNAMENT_ID INT NULL;
GO

-- Track per-user stream likes
CREATE TABLE dbo.STREAM_REACTION (
  REACTION_ID  INT IDENTITY(1,1) NOT NULL,
  STREAM_ID    INT               NOT NULL,
  USER_ID      INT               NOT NULL,
  CREATED_AT   DATETIME2         NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT PK_STREAM_REACTION PRIMARY KEY (REACTION_ID),
  CONSTRAINT UQ_STREAM_REACTION_STREAM_USER UNIQUE (STREAM_ID, USER_ID)
);
GO
