-- Run against GAMERSHUB_TOURNAMENT database
USE GAMERSHUB_TOURNAMENT;
GO

-- Direct team-to-tournament membership (independent of match records)
CREATE TABLE dbo.TOURNAMENT_TEAM (
  ENTRY_ID      INT IDENTITY(1,1) NOT NULL,
  TOURNAMENT_ID INT               NOT NULL,
  TEAM_ID       INT               NOT NULL,
  SEED          INT               NULL,
  JOINED_AT     DATETIME2         NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  CONSTRAINT PK_TOURNAMENT_TEAM PRIMARY KEY (ENTRY_ID),
  CONSTRAINT UQ_TOURNAMENT_TEAM UNIQUE (TOURNAMENT_ID, TEAM_ID)
);
GO
