-- Run against GAMERSHUB_TOURNAMENT database
USE GAMERSHUB_TOURNAMENT;
GO

-- Ensure MATCH table columns allow NULL for deferred data entry
-- Scores and dates are populated after match creation
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MATCH')
BEGIN
  CREATE TABLE dbo.MATCH (
    MATCH_ID      INT IDENTITY(1,1) NOT NULL,
    TOURNAMENT_ID INT               NOT NULL,
    TEAM_A_ID     INT               NOT NULL,
    TEAM_B_ID     INT               NOT NULL,
    TEAM_A_SCORE  INT               NULL,
    TEAM_B_SCORE  INT               NULL,
    MATCH_DATE    DATE              NULL,
    MATCH_TIME    TIME              NULL,
    CREATED_AT    DATETIME2         NOT NULL DEFAULT SYSDATETIME(),
    UPDATED_AT    DATETIME2         NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT PK_MATCH PRIMARY KEY (MATCH_ID),
    CONSTRAINT FK_MATCH_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID)
      REFERENCES dbo.TOURNAMENT(TOURNAMENT_ID),
    CONSTRAINT FK_MATCH_TEAM_A FOREIGN KEY (TEAM_A_ID)
      REFERENCES dbo.TEAM(TEAM_ID),
    CONSTRAINT FK_MATCH_TEAM_B FOREIGN KEY (TEAM_B_ID)
      REFERENCES dbo.TEAM(TEAM_ID)
  );
END
ELSE
BEGIN
  -- Make score and date/time columns nullable if they exist
  ALTER TABLE dbo.MATCH ALTER COLUMN TEAM_A_SCORE INT NULL;
  ALTER TABLE dbo.MATCH ALTER COLUMN TEAM_B_SCORE INT NULL;
  ALTER TABLE dbo.MATCH ALTER COLUMN MATCH_DATE DATE NULL;
  ALTER TABLE dbo.MATCH ALTER COLUMN MATCH_TIME TIME NULL;
END
GO
