USE GAMERSHUB_FEED;

IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'EVENT' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.EVENT (
    EVENT_ID      INT           IDENTITY(1,1) NOT NULL,
    TITLE         NVARCHAR(255) NOT NULL,
    CATEGORY      NVARCHAR(100) NULL,
    DESCRIPTION   NVARCHAR(MAX) NULL,
    EVENT_DATE    DATE          NULL,
    EVENT_TIME    TIME          NULL,
    VENUE         NVARCHAR(255) NULL,
    IS_PUBLISHED  BIT           NOT NULL CONSTRAINT DF_EVENT_PUBLISHED DEFAULT 1,
    CREATED_AT    DATETIME2     NOT NULL CONSTRAINT DF_EVENT_CREATED  DEFAULT SYSUTCDATETIME(),
    UPDATED_AT    DATETIME2     NOT NULL CONSTRAINT DF_EVENT_UPDATED   DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_EVENT PRIMARY KEY (EVENT_ID)
  );

  PRINT 'EVENT table created successfully.';
END
ELSE
BEGIN
  PRINT 'EVENT table already exists — skipped.';
END
