-- Run against GAMERSHUB_TOURNAMENT
-- Creates a key-value MATCH_STATS table for admin-encoded per-match stats.
-- Using key/value allows any game (MLBB kills, Valorant ACS, etc.) without schema changes.
USE GAMERSHUB_TOURNAMENT;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.tables
  WHERE name = 'MATCH_STATS' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.MATCH_STATS (
    STAT_ID       INT           IDENTITY(1,1) NOT NULL,
    MATCH_ID      INT           NOT NULL,
    TEAM_ID       INT           NOT NULL,
    PLAYER_NAME   NVARCHAR(255) NULL,
    STAT_KEY      NVARCHAR(100) NOT NULL,
    STAT_VALUE    NVARCHAR(255) NOT NULL,
    ENTERED_BY    INT           NOT NULL,
    CREATED_AT    DATETIME2     NOT NULL CONSTRAINT DF_STAT_CREATED DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_MATCH_STATS PRIMARY KEY (STAT_ID),
    CONSTRAINT FK_STAT_MATCH FOREIGN KEY (MATCH_ID)
      REFERENCES dbo.MATCH(MATCH_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STAT_TEAM FOREIGN KEY (TEAM_ID)
      REFERENCES dbo.TEAM(TEAM_ID)
  );
END
GO
