-- Run against GAMERSHUB_TOURNAMENT
-- Tournament registration waitlist: public team sign-ups with admin review,
-- payment proof upload, join-code issuance on approval.
USE GAMERSHUB_TOURNAMENT;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.tables
  WHERE name = 'TOURNAMENT_REGISTRATION' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.TOURNAMENT_REGISTRATION (
    REGISTRATION_ID   INT            IDENTITY(1,1) NOT NULL,
    PUBLIC_ID         NVARCHAR(36)   NOT NULL CONSTRAINT DF_REG_PUBLIC_ID DEFAULT (LOWER(NEWID())),
    TOURNAMENT_ID     INT            NOT NULL,
    TEAM_NAME         NVARCHAR(255)  NOT NULL,
    CONTACT_NAME      NVARCHAR(255)  NOT NULL,
    CONTACT_EMAIL     NVARCHAR(255)  NOT NULL,
    CONTACT_PHONE     NVARCHAR(50)   NULL,
    ROSTER_NOTES      NVARCHAR(MAX)  NULL,
    -- admin review state: pending / approved / rejected
    STATUS            NVARCHAR(20)   NOT NULL CONSTRAINT DF_REG_STATUS    DEFAULT 'pending',
    REJECTION_REASON  NVARCHAR(500)  NULL,
    -- payment
    PAYMENT_STATUS    NVARCHAR(20)   NOT NULL CONSTRAINT DF_REG_PAY       DEFAULT 'unpaid',
    PAYMENT_PROOF_URL NVARCHAR(1000) NULL,
    PAYMONGO_LINK_ID  NVARCHAR(255)  NULL,
    -- join code (set on approval, single-use)
    JOIN_CODE         NVARCHAR(20)   NULL,
    JOIN_CODE_USED    BIT            NOT NULL CONSTRAINT DF_REG_CODE_USED DEFAULT 0,
    -- review metadata
    REVIEWED_BY       INT            NULL,
    REVIEWED_AT       DATETIME2      NULL,
    CREATED_AT        DATETIME2      NOT NULL CONSTRAINT DF_REG_CREATED   DEFAULT SYSUTCDATETIME(),
    UPDATED_AT        DATETIME2      NOT NULL CONSTRAINT DF_REG_UPDATED   DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TOURNAMENT_REGISTRATION PRIMARY KEY (REGISTRATION_ID),
    CONSTRAINT UQ_REG_PUBLIC_ID UNIQUE (PUBLIC_ID),
    CONSTRAINT FK_REG_TOURNAMENT FOREIGN KEY (TOURNAMENT_ID)
      REFERENCES dbo.TOURNAMENT(TOURNAMENT_ID)
  );
END
GO
