-- Migration 022: Add ACTIVITY_STATUS column to USER_PROFILE
-- Database: GAMERSHUB_USER

USE GAMERSHUB_USER;
GO

IF NOT EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'dbo'
    AND TABLE_NAME   = 'USER_PROFILE'
    AND COLUMN_NAME  = 'ACTIVITY_STATUS'
)
BEGIN
  ALTER TABLE dbo.USER_PROFILE
    ADD ACTIVITY_STATUS NVARCHAR(100) NULL;
END
GO
