-- Run against GAMERSHUB_TOURNAMENT
-- Stores per-tournament registration fees in centavos and snapshots the fee
-- onto each registration at submit time.
USE GAMERSHUB_TOURNAMENT;
GO

IF COL_LENGTH('dbo.TOURNAMENT', 'REGISTRATION_FEE_AMOUNT') IS NULL
BEGIN
  ALTER TABLE dbo.TOURNAMENT
    ADD REGISTRATION_FEE_AMOUNT INT NOT NULL
      CONSTRAINT DF_TOURNAMENT_REG_FEE DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.TOURNAMENT_REGISTRATION', 'FEE_AMOUNT') IS NULL
BEGIN
  ALTER TABLE dbo.TOURNAMENT_REGISTRATION
    ADD FEE_AMOUNT INT NOT NULL
      CONSTRAINT DF_REG_FEE_AMOUNT DEFAULT (0);
END
GO

UPDATE r
SET r.FEE_AMOUNT = COALESCE(t.REGISTRATION_FEE_AMOUNT, 0)
FROM dbo.TOURNAMENT_REGISTRATION r
INNER JOIN dbo.TOURNAMENT t
  ON t.TOURNAMENT_ID = r.TOURNAMENT_ID
WHERE r.FEE_AMOUNT = 0
  AND COALESCE(t.REGISTRATION_FEE_AMOUNT, 0) > 0;
GO
