-- Run against GAMERSHUB_TOURNAMENT
-- Adds the team banner image URL used by public registration and admin edits.
USE GAMERSHUB_TOURNAMENT;
GO

IF COL_LENGTH('dbo.TOURNAMENT_REGISTRATION', 'TEAM_BANNER_URL') IS NULL
BEGIN
  ALTER TABLE dbo.TOURNAMENT_REGISTRATION
    ADD TEAM_BANNER_URL NVARCHAR(1000) NULL;
END
GO
