-- Migration 026: Add public social profile links to USER_PROFILE
-- Database: GAMERSHUB_USER

USE GAMERSHUB_USER;
GO

IF COL_LENGTH('dbo.USER_PROFILE', 'INSTAGRAM_URL') IS NULL
BEGIN
  ALTER TABLE dbo.USER_PROFILE
    ADD INSTAGRAM_URL NVARCHAR(500) NULL;
END
GO

IF COL_LENGTH('dbo.USER_PROFILE', 'FACEBOOK_URL') IS NULL
BEGIN
  ALTER TABLE dbo.USER_PROFILE
    ADD FACEBOOK_URL NVARCHAR(500) NULL;
END
GO

IF COL_LENGTH('dbo.USER_PROFILE', 'TIKTOK_URL') IS NULL
BEGIN
  ALTER TABLE dbo.USER_PROFILE
    ADD TIKTOK_URL NVARCHAR(500) NULL;
END
GO
